my_file = open('hm_test_2.txt', 'r', encoding='utf-8')
content = my_file.read()
print(f'Содержимое файла:{content}')
my_file = open('hm_test_2.txt', 'r', encoding='utf-8')
content = my_file.readlines()
print(f'Кол-во строк: {len(content)}')
my_file = open('hm_test_2.txt', 'r', encoding='utf-8')
content = my_file.read(len(my_file))
print()